const test                = require('mocha').it
const assert              = require('assert')
const ChessboardTraveling = require('.')

test('chessboard traveling', () => {
    assert(ChessboardTraveling('(1 1)(2 2)') === 2)
    assert(ChessboardTraveling('(1 1)(3 2)') === 3)
    assert(ChessboardTraveling('(1 1)(4 2)') === 4)
    assert(ChessboardTraveling('(1 1)(8 2)') === 8)
    assert(ChessboardTraveling('(1 1)(2 3)') === 3)
    assert(ChessboardTraveling('(1 1)(2 4)') === 4)
    assert(ChessboardTraveling('(1 1)(2 8)') === 8)
    assert(ChessboardTraveling('(2 2)(3 3)') === 2)
    assert(ChessboardTraveling('(2 2)(4 3)') === 3)
    assert(ChessboardTraveling('(2 2)(8 3)') === 7)
    assert(ChessboardTraveling('(2 2)(3 4)') === 3)
    assert(ChessboardTraveling('(2 2)(3 8)') === 7)
    assert(ChessboardTraveling('(1 1)(3 3)') === 6)
    assert(ChessboardTraveling('(1 1)(4 4)') === 20)
    assert(ChessboardTraveling('(1 1)(8 8)') === 3432)
})
